name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # every 24 hours
  workflow_dispatch:     # allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: VIKASRAPARTHI
          outputs: |
            dist/snake.svg
            dist/snake.gif

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
